import "dotenv/config";
import { db } from "./index";
import {
  tournamentStages,
  teams,
  venues,
  matches,
  type NewTournamentStage,
  type NewTeam,
  type NewVenue,
  type NewMatch,
} from "./schema";

async function seed() {
  console.log("🌱 Starting database seed...");

  // Clear existing data (in reverse order of dependencies)
  console.log("🧹 Clearing existing data...");
  await db.delete(matches);
  await db.delete(teams);
  await db.delete(venues);
  await db.delete(tournamentStages);

  // Seed tournament stages
  console.log("📊 Seeding tournament stages...");
  const stages: NewTournamentStage[] = [
    {
      name: "Group Stage",
      slug: "group_stage",
      sortOrder: 1,
      pointsMultiplier: 1.0,
    },
    {
      name: "Round of 16",
      slug: "round_of_16",
      sortOrder: 2,
      pointsMultiplier: 1.5,
    },
    {
      name: "Quarter-finals",
      slug: "quarter_finals",
      sortOrder: 3,
      pointsMultiplier: 2.0,
    },
    {
      name: "Semi-finals",
      slug: "semi_finals",
      sortOrder: 4,
      pointsMultiplier: 2.5,
    },
    {
      name: "Third Place",
      slug: "third_place",
      sortOrder: 5,
      pointsMultiplier: 2.5,
    },
    {
      name: "Final",
      slug: "final",
      sortOrder: 6,
      pointsMultiplier: 3.0,
    },
  ];
  await db.insert(tournamentStages).values(stages);
  console.log(`✅ Inserted ${stages.length} tournament stages`);

  // Seed venues (16 stadiums across USA, Canada, Mexico)
  console.log("🏟️  Seeding venues...");
  const venuesList: NewVenue[] = [
    // USA venues
    {
      name: "MetLife Stadium",
      city: "East Rutherford",
      country: "USA",
      capacity: 82500,
      timezone: "America/New_York",
    },
    {
      name: "SoFi Stadium",
      city: "Inglewood",
      country: "USA",
      capacity: 70240,
      timezone: "America/Los_Angeles",
    },
    {
      name: "AT&T Stadium",
      city: "Arlington",
      country: "USA",
      capacity: 80000,
      timezone: "America/Chicago",
    },
    {
      name: "Mercedes-Benz Stadium",
      city: "Atlanta",
      country: "USA",
      capacity: 71000,
      timezone: "America/New_York",
    },
    {
      name: "Hard Rock Stadium",
      city: "Miami Gardens",
      country: "USA",
      capacity: 64767,
      timezone: "America/New_York",
    },
    {
      name: "NRG Stadium",
      city: "Houston",
      country: "USA",
      capacity: 72220,
      timezone: "America/Chicago",
    },
    {
      name: "Arrowhead Stadium",
      city: "Kansas City",
      country: "USA",
      capacity: 76416,
      timezone: "America/Chicago",
    },
    {
      name: "Lincoln Financial Field",
      city: "Philadelphia",
      country: "USA",
      capacity: 69176,
      timezone: "America/New_York",
    },
    {
      name: "Levi's Stadium",
      city: "Santa Clara",
      country: "USA",
      capacity: 68500,
      timezone: "America/Los_Angeles",
    },
    {
      name: "Gillette Stadium",
      city: "Foxborough",
      country: "USA",
      capacity: 65878,
      timezone: "America/New_York",
    },
    {
      name: "Lumen Field",
      city: "Seattle",
      country: "USA",
      capacity: 68740,
      timezone: "America/Los_Angeles",
    },
    // Canada venues
    {
      name: "BMO Field",
      city: "Toronto",
      country: "Canada",
      capacity: 45500,
      timezone: "America/Toronto",
    },
    {
      name: "BC Place",
      city: "Vancouver",
      country: "Canada",
      capacity: 54500,
      timezone: "America/Vancouver",
    },
    // Mexico venues
    {
      name: "Estadio Azteca",
      city: "Mexico City",
      country: "Mexico",
      capacity: 87523,
      timezone: "America/Mexico_City",
    },
    {
      name: "Estadio BBVA",
      city: "Monterrey",
      country: "Mexico",
      capacity: 53500,
      timezone: "America/Monterrey",
    },
    {
      name: "Estadio Akron",
      city: "Guadalajara",
      country: "Mexico",
      capacity: 46232,
      timezone: "America/Mexico_City",
    },
  ];
  await db.insert(venues).values(venuesList);
  console.log(`✅ Inserted ${venuesList.length} venues`);

  // Seed teams (48 teams in 12 groups of 4)
  // Based on official FIFA World Cup 2026 draw
  console.log("⚽ Seeding teams...");
  const teamsList: NewTeam[] = [
    // Group A
    {
      name: "Mexico",
      code: "MEX",
      groupLetter: "A",
      confederation: "CONCACAF",
      fifaRanking: 15,
      flagUrl: "https://flagcdn.com/w320/mx.png",
    },
    {
      name: "South Africa",
      code: "RSA",
      groupLetter: "A",
      confederation: "CAF",
      fifaRanking: 57,
      flagUrl: "https://flagcdn.com/w320/za.png",
    },
    {
      name: "Korea Republic",
      code: "KOR",
      groupLetter: "A",
      confederation: "AFC",
      fifaRanking: 23,
      flagUrl: "https://flagcdn.com/w320/kr.png",
    },
    {
      name: "UEFA Playoff Winner D",
      code: "UEFA_PO_D",
      groupLetter: "A",
      confederation: "UEFA",
      fifaRanking: 999,
      flagUrl: "https://flagcdn.com/w320/xx.png",
    },
    // Group B
    {
      name: "Canada",
      code: "CAN",
      groupLetter: "B",
      confederation: "CONCACAF",
      fifaRanking: 48,
      flagUrl: "https://flagcdn.com/w320/ca.png",
    },
    {
      name: "Switzerland",
      code: "SUI",
      groupLetter: "B",
      confederation: "UEFA",
      fifaRanking: 17,
      flagUrl: "https://flagcdn.com/w320/ch.png",
    },
    {
      name: "Qatar",
      code: "QAT",
      groupLetter: "B",
      confederation: "AFC",
      fifaRanking: 61,
      flagUrl: "https://flagcdn.com/w320/qa.png",
    },
    {
      name: "UEFA Playoff Winner A",
      code: "UEFA_PO_A",
      groupLetter: "B",
      confederation: "UEFA",
      fifaRanking: 999,
      flagUrl: "https://flagcdn.com/w320/xx.png",
    },
    // Group C
    {
      name: "Brazil",
      code: "BRA",
      groupLetter: "C",
      confederation: "CONMEBOL",
      fifaRanking: 4,
      flagUrl: "https://flagcdn.com/w320/br.png",
    },
    {
      name: "Morocco",
      code: "MAR",
      groupLetter: "C",
      confederation: "CAF",
      fifaRanking: 14,
      flagUrl: "https://flagcdn.com/w320/ma.png",
    },
    {
      name: "Haiti",
      code: "HAI",
      groupLetter: "C",
      confederation: "CONCACAF",
      fifaRanking: 85,
      flagUrl: "https://flagcdn.com/w320/ht.png",
    },
    {
      name: "Scotland",
      code: "SCO",
      groupLetter: "C",
      confederation: "UEFA",
      fifaRanking: 34,
      flagUrl: "https://flagcdn.com/w320/gb-sct.png",
    },
    // Group D
    {
      name: "USA",
      code: "USA",
      groupLetter: "D",
      confederation: "CONCACAF",
      fifaRanking: 13,
      flagUrl: "https://flagcdn.com/w320/us.png",
    },
    {
      name: "Paraguay",
      code: "PAR",
      groupLetter: "D",
      confederation: "CONMEBOL",
      fifaRanking: 58,
      flagUrl: "https://flagcdn.com/w320/py.png",
    },
    {
      name: "Australia",
      code: "AUS",
      groupLetter: "D",
      confederation: "AFC",
      fifaRanking: 26,
      flagUrl: "https://flagcdn.com/w320/au.png",
    },
    {
      name: "UEFA Playoff Winner C",
      code: "UEFA_PO_C",
      groupLetter: "D",
      confederation: "UEFA",
      fifaRanking: 999,
      flagUrl: "https://flagcdn.com/w320/xx.png",
    },
    // Group E
    {
      name: "Germany",
      code: "GER",
      groupLetter: "E",
      confederation: "UEFA",
      fifaRanking: 10,
      flagUrl: "https://flagcdn.com/w320/de.png",
    },
    {
      name: "Curaçao",
      code: "CUW",
      groupLetter: "E",
      confederation: "CONCACAF",
      fifaRanking: 90,
      flagUrl: "https://flagcdn.com/w320/cw.png",
    },
    {
      name: "Ivory Coast",
      code: "CIV",
      groupLetter: "E",
      confederation: "CAF",
      fifaRanking: 39,
      flagUrl: "https://flagcdn.com/w320/ci.png",
    },
    {
      name: "Ecuador",
      code: "ECU",
      groupLetter: "E",
      confederation: "CONMEBOL",
      fifaRanking: 30,
      flagUrl: "https://flagcdn.com/w320/ec.png",
    },
    // Group F
    {
      name: "Netherlands",
      code: "NED",
      groupLetter: "F",
      confederation: "UEFA",
      fifaRanking: 8,
      flagUrl: "https://flagcdn.com/w320/nl.png",
    },
    {
      name: "Japan",
      code: "JPN",
      groupLetter: "F",
      confederation: "AFC",
      fifaRanking: 20,
      flagUrl: "https://flagcdn.com/w320/jp.png",
    },
    {
      name: "Tunisia",
      code: "TUN",
      groupLetter: "F",
      confederation: "CAF",
      fifaRanking: 47,
      flagUrl: "https://flagcdn.com/w320/tn.png",
    },
    {
      name: "UEFA Playoff Winner B",
      code: "UEFA_PO_B",
      groupLetter: "F",
      confederation: "UEFA",
      fifaRanking: 999,
      flagUrl: "https://flagcdn.com/w320/xx.png",
    },
    // Group G
    {
      name: "Belgium",
      code: "BEL",
      groupLetter: "G",
      confederation: "UEFA",
      fifaRanking: 7,
      flagUrl: "https://flagcdn.com/w320/be.png",
    },
    {
      name: "Egypt",
      code: "EGY",
      groupLetter: "G",
      confederation: "CAF",
      fifaRanking: 36,
      flagUrl: "https://flagcdn.com/w320/eg.png",
    },
    {
      name: "Iran",
      code: "IRN",
      groupLetter: "G",
      confederation: "AFC",
      fifaRanking: 22,
      flagUrl: "https://flagcdn.com/w320/ir.png",
    },
    {
      name: "New Zealand",
      code: "NZL",
      groupLetter: "G",
      confederation: "OFC",
      fifaRanking: 94,
      flagUrl: "https://flagcdn.com/w320/nz.png",
    },
    // Group H
    {
      name: "Spain",
      code: "ESP",
      groupLetter: "H",
      confederation: "UEFA",
      fifaRanking: 3,
      flagUrl: "https://flagcdn.com/w320/es.png",
    },
    {
      name: "Cape Verde",
      code: "CPV",
      groupLetter: "H",
      confederation: "CAF",
      fifaRanking: 73,
      flagUrl: "https://flagcdn.com/w320/cv.png",
    },
    {
      name: "Saudi Arabia",
      code: "KSA",
      groupLetter: "H",
      confederation: "AFC",
      fifaRanking: 56,
      flagUrl: "https://flagcdn.com/w320/sa.png",
    },
    {
      name: "Uruguay",
      code: "URU",
      groupLetter: "H",
      confederation: "CONMEBOL",
      fifaRanking: 11,
      flagUrl: "https://flagcdn.com/w320/uy.png",
    },
    // Group I
    {
      name: "France",
      code: "FRA",
      groupLetter: "I",
      confederation: "UEFA",
      fifaRanking: 2,
      flagUrl: "https://flagcdn.com/w320/fr.png",
    },
    {
      name: "Senegal",
      code: "SEN",
      groupLetter: "I",
      confederation: "CAF",
      fifaRanking: 21,
      flagUrl: "https://flagcdn.com/w320/sn.png",
    },
    {
      name: "Norway",
      code: "NOR",
      groupLetter: "I",
      confederation: "UEFA",
      fifaRanking: 44,
      flagUrl: "https://flagcdn.com/w320/no.png",
    },
    {
      name: "Intercontinental Playoff Winner 2",
      code: "IC_PO_2",
      groupLetter: "I",
      confederation: "TBD",
      fifaRanking: 999,
      flagUrl: "https://flagcdn.com/w320/xx.png",
    },
    // Group J
    {
      name: "Argentina",
      code: "ARG",
      groupLetter: "J",
      confederation: "CONMEBOL",
      fifaRanking: 1,
      flagUrl: "https://flagcdn.com/w320/ar.png",
    },
    {
      name: "Algeria",
      code: "ALG",
      groupLetter: "J",
      confederation: "CAF",
      fifaRanking: 43,
      flagUrl: "https://flagcdn.com/w320/dz.png",
    },
    {
      name: "Austria",
      code: "AUT",
      groupLetter: "J",
      confederation: "UEFA",
      fifaRanking: 24,
      flagUrl: "https://flagcdn.com/w320/at.png",
    },
    {
      name: "Jordan",
      code: "JOR",
      groupLetter: "J",
      confederation: "AFC",
      fifaRanking: 68,
      flagUrl: "https://flagcdn.com/w320/jo.png",
    },
    // Group K
    {
      name: "Portugal",
      code: "POR",
      groupLetter: "K",
      confederation: "UEFA",
      fifaRanking: 6,
      flagUrl: "https://flagcdn.com/w320/pt.png",
    },
    {
      name: "Colombia",
      code: "COL",
      groupLetter: "K",
      confederation: "CONMEBOL",
      fifaRanking: 9,
      flagUrl: "https://flagcdn.com/w320/co.png",
    },
    {
      name: "Uzbekistan",
      code: "UZB",
      groupLetter: "K",
      confederation: "AFC",
      fifaRanking: 62,
      flagUrl: "https://flagcdn.com/w320/uz.png",
    },
    {
      name: "Intercontinental Playoff Winner 1",
      code: "IC_PO_1",
      groupLetter: "K",
      confederation: "TBD",
      fifaRanking: 999,
      flagUrl: "https://flagcdn.com/w320/xx.png",
    },
    // Group L
    {
      name: "England",
      code: "ENG",
      groupLetter: "L",
      confederation: "UEFA",
      fifaRanking: 5,
      flagUrl: "https://flagcdn.com/w320/gb-eng.png",
    },
    {
      name: "Croatia",
      code: "CRO",
      groupLetter: "L",
      confederation: "UEFA",
      fifaRanking: 12,
      flagUrl: "https://flagcdn.com/w320/hr.png",
    },
    {
      name: "Ghana",
      code: "GHA",
      groupLetter: "L",
      confederation: "CAF",
      fifaRanking: 64,
      flagUrl: "https://flagcdn.com/w320/gh.png",
    },
    {
      name: "Panama",
      code: "PAN",
      groupLetter: "L",
      confederation: "CONCACAF",
      fifaRanking: 52,
      flagUrl: "https://flagcdn.com/w320/pa.png",
    },
  ];
  await db.insert(teams).values(teamsList);
  const insertedTeams = await db.select().from(teams);
  console.log(`✅ Inserted ${teamsList.length} teams`);

  // Create team lookup map for matches
  const teamIdByCode = new Map<string, number>();
  insertedTeams.forEach((team) => teamIdByCode.set(team.code, team.id));

  // Create venue lookup map for matches
  const insertedVenues = await db.select().from(venues);
  const venueIdByCity = new Map<string, number>();
  insertedVenues.forEach((venue) => venueIdByCity.set(venue.city, venue.id));

  // Create stage lookup map for matches
  const insertedStages = await db.select().from(tournamentStages);
  const stageIdBySlug = new Map<string, number>();
  insertedStages.forEach((stage) => stageIdBySlug.set(stage.slug, stage.id));

  // Seed matches (104 total: 72 group stage + 32 knockout)
  console.log("⚽ Seeding matches...");

  // Helper type for match data before ID resolution
  type MatchData = {
    matchNumber: number;
    stageSlug: string;
    homeTeamCode?: string;
    awayTeamCode?: string;
    homeTeamPlaceholder?: string | null;
    awayTeamPlaceholder?: string | null;
    venueCity: string;
    scheduledAt: Date;
    status: "scheduled" | "live" | "finished";
  };

  const matchesData: MatchData[] = [
    // GROUP STAGE MATCHES (1-72)
    // Group A
    {
      matchNumber: 1,
      stageSlug: "group_stage",
      homeTeamCode: "MEX",
      awayTeamCode: "RSA",
      venueCity: "Mexico City",
      scheduledAt: new Date("2026-06-11T15:00:00-05:00"),
      status: "scheduled",
    },
    {
      matchNumber: 2,
      stageSlug: "group_stage",
      homeTeamCode: "KOR",
      awayTeamCode: "UEFA_PO_D",
      venueCity: "Guadalajara",
      scheduledAt: new Date("2026-06-11T22:00:00-06:00"),
      status: "scheduled",
    },
    {
      matchNumber: 13,
      stageSlug: "group_stage",
      homeTeamCode: "MEX",
      awayTeamCode: "KOR",
      venueCity: "Mexico City",
      scheduledAt: new Date("2026-06-17T15:00:00-05:00"),
      status: "scheduled",
    },
    {
      matchNumber: 14,
      stageSlug: "group_stage",
      homeTeamCode: "RSA",
      awayTeamCode: "UEFA_PO_D",
      venueCity: "Monterrey",
      scheduledAt: new Date("2026-06-17T18:00:00-06:00"),
      status: "scheduled",
    },
    {
      matchNumber: 25,
      stageSlug: "group_stage",
      homeTeamCode: "RSA",
      awayTeamCode: "KOR",
      venueCity: "Guadalajara",
      scheduledAt: new Date("2026-06-23T15:00:00-06:00"),
      status: "scheduled",
    },
    {
      matchNumber: 26,
      stageSlug: "group_stage",
      homeTeamCode: "UEFA_PO_D",
      awayTeamCode: "MEX",
      venueCity: "Monterrey",
      scheduledAt: new Date("2026-06-23T15:00:00-06:00"),
      status: "scheduled",
    },
    // Group B
    {
      matchNumber: 3,
      stageSlug: "group_stage",
      homeTeamCode: "CAN",
      awayTeamCode: "SUI",
      venueCity: "Toronto",
      scheduledAt: new Date("2026-06-12T15:00:00-04:00"),
      status: "scheduled",
    },
    {
      matchNumber: 4,
      stageSlug: "group_stage",
      homeTeamCode: "QAT",
      awayTeamCode: "UEFA_PO_A",
      venueCity: "Vancouver",
      scheduledAt: new Date("2026-06-12T18:00:00-07:00"),
      status: "scheduled",
    },
    {
      matchNumber: 15,
      stageSlug: "group_stage",
      homeTeamCode: "CAN",
      awayTeamCode: "QAT",
      venueCity: "Toronto",
      scheduledAt: new Date("2026-06-18T15:00:00-04:00"),
      status: "scheduled",
    },
    {
      matchNumber: 16,
      stageSlug: "group_stage",
      homeTeamCode: "SUI",
      awayTeamCode: "UEFA_PO_A",
      venueCity: "Vancouver",
      scheduledAt: new Date("2026-06-18T18:00:00-07:00"),
      status: "scheduled",
    },
    {
      matchNumber: 27,
      stageSlug: "group_stage",
      homeTeamCode: "SUI",
      awayTeamCode: "QAT",
      venueCity: "Toronto",
      scheduledAt: new Date("2026-06-24T19:00:00-04:00"),
      status: "scheduled",
    },
    {
      matchNumber: 28,
      stageSlug: "group_stage",
      homeTeamCode: "UEFA_PO_A",
      awayTeamCode: "CAN",
      venueCity: "Vancouver",
      scheduledAt: new Date("2026-06-24T19:00:00-07:00"),
      status: "scheduled",
    },
    // Group C
    {
      matchNumber: 5,
      stageSlug: "group_stage",
      homeTeamCode: "BRA",
      awayTeamCode: "MAR",
      venueCity: "Inglewood",
      scheduledAt: new Date("2026-06-13T15:00:00-07:00"),
      status: "scheduled",
    },
    {
      matchNumber: 6,
      stageSlug: "group_stage",
      homeTeamCode: "HAI",
      awayTeamCode: "SCO",
      venueCity: "Santa Clara",
      scheduledAt: new Date("2026-06-13T18:00:00-07:00"),
      status: "scheduled",
    },
    {
      matchNumber: 17,
      stageSlug: "group_stage",
      homeTeamCode: "BRA",
      awayTeamCode: "HAI",
      venueCity: "Inglewood",
      scheduledAt: new Date("2026-06-19T15:00:00-07:00"),
      status: "scheduled",
    },
    {
      matchNumber: 18,
      stageSlug: "group_stage",
      homeTeamCode: "MAR",
      awayTeamCode: "SCO",
      venueCity: "Seattle",
      scheduledAt: new Date("2026-06-19T18:00:00-07:00"),
      status: "scheduled",
    },
    {
      matchNumber: 29,
      stageSlug: "group_stage",
      homeTeamCode: "MAR",
      awayTeamCode: "HAI",
      venueCity: "Santa Clara",
      scheduledAt: new Date("2026-06-25T19:00:00-07:00"),
      status: "scheduled",
    },
    {
      matchNumber: 30,
      stageSlug: "group_stage",
      homeTeamCode: "SCO",
      awayTeamCode: "BRA",
      venueCity: "Seattle",
      scheduledAt: new Date("2026-06-25T19:00:00-07:00"),
      status: "scheduled",
    },
    // Group D
    {
      matchNumber: 7,
      stageSlug: "group_stage",
      homeTeamCode: "USA",
      awayTeamCode: "PAR",
      venueCity: "Inglewood",
      scheduledAt: new Date("2026-06-12T21:00:00-07:00"),
      status: "scheduled",
    },
    {
      matchNumber: 8,
      stageSlug: "group_stage",
      homeTeamCode: "AUS",
      awayTeamCode: "UEFA_PO_C",
      venueCity: "Seattle",
      scheduledAt: new Date("2026-06-13T21:00:00-07:00"),
      status: "scheduled",
    },
    {
      matchNumber: 19,
      stageSlug: "group_stage",
      homeTeamCode: "USA",
      awayTeamCode: "AUS",
      venueCity: "Santa Clara",
      scheduledAt: new Date("2026-06-20T15:00:00-07:00"),
      status: "scheduled",
    },
    {
      matchNumber: 20,
      stageSlug: "group_stage",
      homeTeamCode: "PAR",
      awayTeamCode: "UEFA_PO_C",
      venueCity: "Seattle",
      scheduledAt: new Date("2026-06-20T18:00:00-07:00"),
      status: "scheduled",
    },
    {
      matchNumber: 31,
      stageSlug: "group_stage",
      homeTeamCode: "PAR",
      awayTeamCode: "AUS",
      venueCity: "Inglewood",
      scheduledAt: new Date("2026-06-26T19:00:00-07:00"),
      status: "scheduled",
    },
    {
      matchNumber: 32,
      stageSlug: "group_stage",
      homeTeamCode: "UEFA_PO_C",
      awayTeamCode: "USA",
      venueCity: "Santa Clara",
      scheduledAt: new Date("2026-06-26T19:00:00-07:00"),
      status: "scheduled",
    },
    // Group E
    {
      matchNumber: 9,
      stageSlug: "group_stage",
      homeTeamCode: "GER",
      awayTeamCode: "CUW",
      venueCity: "Philadelphia",
      scheduledAt: new Date("2026-06-14T13:00:00-04:00"),
      status: "scheduled",
    },
    {
      matchNumber: 10,
      stageSlug: "group_stage",
      homeTeamCode: "CIV",
      awayTeamCode: "ECU",
      venueCity: "East Rutherford",
      scheduledAt: new Date("2026-06-14T16:00:00-04:00"),
      status: "scheduled",
    },
    {
      matchNumber: 21,
      stageSlug: "group_stage",
      homeTeamCode: "GER",
      awayTeamCode: "CIV",
      venueCity: "East Rutherford",
      scheduledAt: new Date("2026-06-20T19:00:00-04:00"),
      status: "scheduled",
    },
    {
      matchNumber: 22,
      stageSlug: "group_stage",
      homeTeamCode: "CUW",
      awayTeamCode: "ECU",
      venueCity: "Philadelphia",
      scheduledAt: new Date("2026-06-20T22:00:00-04:00"),
      status: "scheduled",
    },
    {
      matchNumber: 33,
      stageSlug: "group_stage",
      homeTeamCode: "CUW",
      awayTeamCode: "CIV",
      venueCity: "East Rutherford",
      scheduledAt: new Date("2026-06-26T19:00:00-04:00"),
      status: "scheduled",
    },
    {
      matchNumber: 34,
      stageSlug: "group_stage",
      homeTeamCode: "ECU",
      awayTeamCode: "GER",
      venueCity: "Philadelphia",
      scheduledAt: new Date("2026-06-26T19:00:00-04:00"),
      status: "scheduled",
    },
    // Group F
    {
      matchNumber: 11,
      stageSlug: "group_stage",
      homeTeamCode: "NED",
      awayTeamCode: "JPN",
      venueCity: "Arlington",
      scheduledAt: new Date("2026-06-15T13:00:00-05:00"),
      status: "scheduled",
    },
    {
      matchNumber: 12,
      stageSlug: "group_stage",
      homeTeamCode: "TUN",
      awayTeamCode: "UEFA_PO_B",
      venueCity: "Kansas City",
      scheduledAt: new Date("2026-06-15T16:00:00-05:00"),
      status: "scheduled",
    },
    {
      matchNumber: 23,
      stageSlug: "group_stage",
      homeTeamCode: "NED",
      awayTeamCode: "TUN",
      venueCity: "Kansas City",
      scheduledAt: new Date("2026-06-21T13:00:00-05:00"),
      status: "scheduled",
    },
    {
      matchNumber: 24,
      stageSlug: "group_stage",
      homeTeamCode: "JPN",
      awayTeamCode: "UEFA_PO_B",
      venueCity: "Arlington",
      scheduledAt: new Date("2026-06-21T16:00:00-05:00"),
      status: "scheduled",
    },
    {
      matchNumber: 35,
      stageSlug: "group_stage",
      homeTeamCode: "JPN",
      awayTeamCode: "TUN",
      venueCity: "Kansas City",
      scheduledAt: new Date("2026-06-27T15:00:00-05:00"),
      status: "scheduled",
    },
    {
      matchNumber: 36,
      stageSlug: "group_stage",
      homeTeamCode: "UEFA_PO_B",
      awayTeamCode: "NED",
      venueCity: "Arlington",
      scheduledAt: new Date("2026-06-27T15:00:00-05:00"),
      status: "scheduled",
    },
    // Group G
    {
      matchNumber: 37,
      stageSlug: "group_stage",
      homeTeamCode: "BEL",
      awayTeamCode: "EGY",
      venueCity: "Houston",
      scheduledAt: new Date("2026-06-14T19:00:00-05:00"),
      status: "scheduled",
    },
    {
      matchNumber: 38,
      stageSlug: "group_stage",
      homeTeamCode: "IRN",
      awayTeamCode: "NZL",
      venueCity: "Kansas City",
      scheduledAt: new Date("2026-06-14T22:00:00-05:00"),
      status: "scheduled",
    },
    {
      matchNumber: 39,
      stageSlug: "group_stage",
      homeTeamCode: "BEL",
      awayTeamCode: "IRN",
      venueCity: "Kansas City",
      scheduledAt: new Date("2026-06-21T19:00:00-05:00"),
      status: "scheduled",
    },
    {
      matchNumber: 40,
      stageSlug: "group_stage",
      homeTeamCode: "EGY",
      awayTeamCode: "NZL",
      venueCity: "Houston",
      scheduledAt: new Date("2026-06-21T22:00:00-05:00"),
      status: "scheduled",
    },
    {
      matchNumber: 41,
      stageSlug: "group_stage",
      homeTeamCode: "EGY",
      awayTeamCode: "IRN",
      venueCity: "Kansas City",
      scheduledAt: new Date("2026-06-27T19:00:00-05:00"),
      status: "scheduled",
    },
    {
      matchNumber: 42,
      stageSlug: "group_stage",
      homeTeamCode: "NZL",
      awayTeamCode: "BEL",
      venueCity: "Houston",
      scheduledAt: new Date("2026-06-27T19:00:00-05:00"),
      status: "scheduled",
    },
    // Group H
    {
      matchNumber: 43,
      stageSlug: "group_stage",
      homeTeamCode: "ESP",
      awayTeamCode: "CPV",
      venueCity: "Miami Gardens",
      scheduledAt: new Date("2026-06-15T19:00:00-04:00"),
      status: "scheduled",
    },
    {
      matchNumber: 44,
      stageSlug: "group_stage",
      homeTeamCode: "KSA",
      awayTeamCode: "URU",
      venueCity: "Atlanta",
      scheduledAt: new Date("2026-06-15T22:00:00-04:00"),
      status: "scheduled",
    },
    {
      matchNumber: 45,
      stageSlug: "group_stage",
      homeTeamCode: "ESP",
      awayTeamCode: "KSA",
      venueCity: "Atlanta",
      scheduledAt: new Date("2026-06-22T13:00:00-04:00"),
      status: "scheduled",
    },
    {
      matchNumber: 46,
      stageSlug: "group_stage",
      homeTeamCode: "CPV",
      awayTeamCode: "URU",
      venueCity: "Miami Gardens",
      scheduledAt: new Date("2026-06-22T16:00:00-04:00"),
      status: "scheduled",
    },
    {
      matchNumber: 47,
      stageSlug: "group_stage",
      homeTeamCode: "CPV",
      awayTeamCode: "KSA",
      venueCity: "Atlanta",
      scheduledAt: new Date("2026-06-27T19:00:00-04:00"),
      status: "scheduled",
    },
    {
      matchNumber: 48,
      stageSlug: "group_stage",
      homeTeamCode: "URU",
      awayTeamCode: "ESP",
      venueCity: "Miami Gardens",
      scheduledAt: new Date("2026-06-27T19:00:00-04:00"),
      status: "scheduled",
    },
    // Group I
    {
      matchNumber: 49,
      stageSlug: "group_stage",
      homeTeamCode: "FRA",
      awayTeamCode: "SEN",
      venueCity: "Foxborough",
      scheduledAt: new Date("2026-06-16T13:00:00-04:00"),
      status: "scheduled",
    },
    {
      matchNumber: 50,
      stageSlug: "group_stage",
      homeTeamCode: "NOR",
      awayTeamCode: "IC_PO_2",
      venueCity: "East Rutherford",
      scheduledAt: new Date("2026-06-16T16:00:00-04:00"),
      status: "scheduled",
    },
    {
      matchNumber: 51,
      stageSlug: "group_stage",
      homeTeamCode: "FRA",
      awayTeamCode: "NOR",
      venueCity: "East Rutherford",
      scheduledAt: new Date("2026-06-22T19:00:00-04:00"),
      status: "scheduled",
    },
    {
      matchNumber: 52,
      stageSlug: "group_stage",
      homeTeamCode: "SEN",
      awayTeamCode: "IC_PO_2",
      venueCity: "Foxborough",
      scheduledAt: new Date("2026-06-22T22:00:00-04:00"),
      status: "scheduled",
    },
    {
      matchNumber: 53,
      stageSlug: "group_stage",
      homeTeamCode: "SEN",
      awayTeamCode: "NOR",
      venueCity: "East Rutherford",
      scheduledAt: new Date("2026-06-27T15:00:00-04:00"),
      status: "scheduled",
    },
    {
      matchNumber: 54,
      stageSlug: "group_stage",
      homeTeamCode: "IC_PO_2",
      awayTeamCode: "FRA",
      venueCity: "Foxborough",
      scheduledAt: new Date("2026-06-27T15:00:00-04:00"),
      status: "scheduled",
    },
    // Group J
    {
      matchNumber: 55,
      stageSlug: "group_stage",
      homeTeamCode: "ARG",
      awayTeamCode: "ALG",
      venueCity: "East Rutherford",
      scheduledAt: new Date("2026-06-16T19:00:00-04:00"),
      status: "scheduled",
    },
    {
      matchNumber: 56,
      stageSlug: "group_stage",
      homeTeamCode: "AUT",
      awayTeamCode: "JOR",
      venueCity: "Philadelphia",
      scheduledAt: new Date("2026-06-16T22:00:00-04:00"),
      status: "scheduled",
    },
    {
      matchNumber: 57,
      stageSlug: "group_stage",
      homeTeamCode: "ARG",
      awayTeamCode: "AUT",
      venueCity: "Philadelphia",
      scheduledAt: new Date("2026-06-23T13:00:00-04:00"),
      status: "scheduled",
    },
    {
      matchNumber: 58,
      stageSlug: "group_stage",
      homeTeamCode: "ALG",
      awayTeamCode: "JOR",
      venueCity: "East Rutherford",
      scheduledAt: new Date("2026-06-23T16:00:00-04:00"),
      status: "scheduled",
    },
    {
      matchNumber: 59,
      stageSlug: "group_stage",
      homeTeamCode: "ALG",
      awayTeamCode: "AUT",
      venueCity: "Philadelphia",
      scheduledAt: new Date("2026-06-27T15:00:00-04:00"),
      status: "scheduled",
    },
    {
      matchNumber: 60,
      stageSlug: "group_stage",
      homeTeamCode: "JOR",
      awayTeamCode: "ARG",
      venueCity: "East Rutherford",
      scheduledAt: new Date("2026-06-27T15:00:00-04:00"),
      status: "scheduled",
    },
    // Group K
    {
      matchNumber: 61,
      stageSlug: "group_stage",
      homeTeamCode: "POR",
      awayTeamCode: "COL",
      venueCity: "Atlanta",
      scheduledAt: new Date("2026-06-17T13:00:00-04:00"),
      status: "scheduled",
    },
    {
      matchNumber: 62,
      stageSlug: "group_stage",
      homeTeamCode: "UZB",
      awayTeamCode: "IC_PO_1",
      venueCity: "Miami Gardens",
      scheduledAt: new Date("2026-06-17T16:00:00-04:00"),
      status: "scheduled",
    },
    {
      matchNumber: 63,
      stageSlug: "group_stage",
      homeTeamCode: "POR",
      awayTeamCode: "UZB",
      venueCity: "Miami Gardens",
      scheduledAt: new Date("2026-06-23T19:00:00-04:00"),
      status: "scheduled",
    },
    {
      matchNumber: 64,
      stageSlug: "group_stage",
      homeTeamCode: "COL",
      awayTeamCode: "IC_PO_1",
      venueCity: "Atlanta",
      scheduledAt: new Date("2026-06-23T22:00:00-04:00"),
      status: "scheduled",
    },
    {
      matchNumber: 65,
      stageSlug: "group_stage",
      homeTeamCode: "COL",
      awayTeamCode: "UZB",
      venueCity: "Miami Gardens",
      scheduledAt: new Date("2026-06-27T19:30:00-04:00"),
      status: "scheduled",
    },
    {
      matchNumber: 66,
      stageSlug: "group_stage",
      homeTeamCode: "IC_PO_1",
      awayTeamCode: "POR",
      venueCity: "Atlanta",
      scheduledAt: new Date("2026-06-27T19:30:00-04:00"),
      status: "scheduled",
    },
    // Group L
    {
      matchNumber: 67,
      stageSlug: "group_stage",
      homeTeamCode: "ENG",
      awayTeamCode: "CRO",
      venueCity: "Arlington",
      scheduledAt: new Date("2026-06-17T19:00:00-05:00"),
      status: "scheduled",
    },
    {
      matchNumber: 68,
      stageSlug: "group_stage",
      homeTeamCode: "GHA",
      awayTeamCode: "PAN",
      venueCity: "Houston",
      scheduledAt: new Date("2026-06-17T22:00:00-05:00"),
      status: "scheduled",
    },
    {
      matchNumber: 69,
      stageSlug: "group_stage",
      homeTeamCode: "ENG",
      awayTeamCode: "GHA",
      venueCity: "Houston",
      scheduledAt: new Date("2026-06-24T13:00:00-05:00"),
      status: "scheduled",
    },
    {
      matchNumber: 70,
      stageSlug: "group_stage",
      homeTeamCode: "CRO",
      awayTeamCode: "PAN",
      venueCity: "Arlington",
      scheduledAt: new Date("2026-06-24T16:00:00-05:00"),
      status: "scheduled",
    },
    {
      matchNumber: 71,
      stageSlug: "group_stage",
      homeTeamCode: "CRO",
      awayTeamCode: "GHA",
      venueCity: "Houston",
      scheduledAt: new Date("2026-06-27T19:30:00-05:00"),
      status: "scheduled",
    },
    {
      matchNumber: 72,
      stageSlug: "group_stage",
      homeTeamCode: "PAN",
      awayTeamCode: "ENG",
      venueCity: "Arlington",
      scheduledAt: new Date("2026-06-27T19:30:00-05:00"),
      status: "scheduled",
    },

    // KNOCKOUT STAGE MATCHES (73-104)
    // Round of 16 (Matches 73-88)
    {
      matchNumber: 73,
      stageSlug: "round_of_16",
      homeTeamPlaceholder: "1st Group A",
      awayTeamPlaceholder: "2nd Group B",
      venueCity: "Inglewood",
      scheduledAt: new Date("2026-06-28T15:00:00-07:00"),
      status: "scheduled",
    },
    {
      matchNumber: 74,
      stageSlug: "round_of_16",
      homeTeamPlaceholder: "1st Group C",
      awayTeamPlaceholder: "2nd Group D",
      venueCity: "Arlington",
      scheduledAt: new Date("2026-06-28T19:00:00-05:00"),
      status: "scheduled",
    },
    {
      matchNumber: 75,
      stageSlug: "round_of_16",
      homeTeamPlaceholder: "1st Group E",
      awayTeamPlaceholder: "2nd Group F",
      venueCity: "East Rutherford",
      scheduledAt: new Date("2026-06-29T13:00:00-04:00"),
      status: "scheduled",
    },
    {
      matchNumber: 76,
      stageSlug: "round_of_16",
      homeTeamPlaceholder: "1st Group G",
      awayTeamPlaceholder: "2nd Group H",
      venueCity: "Atlanta",
      scheduledAt: new Date("2026-06-29T19:00:00-04:00"),
      status: "scheduled",
    },
    {
      matchNumber: 77,
      stageSlug: "round_of_16",
      homeTeamPlaceholder: "1st Group I",
      awayTeamPlaceholder: "2nd Group J",
      venueCity: "Foxborough",
      scheduledAt: new Date("2026-06-30T13:00:00-04:00"),
      status: "scheduled",
    },
    {
      matchNumber: 78,
      stageSlug: "round_of_16",
      homeTeamPlaceholder: "1st Group K",
      awayTeamPlaceholder: "2nd Group L",
      venueCity: "Miami Gardens",
      scheduledAt: new Date("2026-06-30T19:00:00-04:00"),
      status: "scheduled",
    },
    {
      matchNumber: 79,
      stageSlug: "round_of_16",
      homeTeamPlaceholder: "1st Group B",
      awayTeamPlaceholder: "2nd Group A",
      venueCity: "Toronto",
      scheduledAt: new Date("2026-07-01T15:00:00-04:00"),
      status: "scheduled",
    },
    {
      matchNumber: 80,
      stageSlug: "round_of_16",
      homeTeamPlaceholder: "1st Group D",
      awayTeamPlaceholder: "2nd Group C",
      venueCity: "Santa Clara",
      scheduledAt: new Date("2026-07-01T19:00:00-07:00"),
      status: "scheduled",
    },
    {
      matchNumber: 81,
      stageSlug: "round_of_16",
      homeTeamPlaceholder: "1st Group F",
      awayTeamPlaceholder: "2nd Group E",
      venueCity: "Kansas City",
      scheduledAt: new Date("2026-07-02T13:00:00-05:00"),
      status: "scheduled",
    },
    {
      matchNumber: 82,
      stageSlug: "round_of_16",
      homeTeamPlaceholder: "1st Group H",
      awayTeamPlaceholder: "2nd Group G",
      venueCity: "Houston",
      scheduledAt: new Date("2026-07-02T19:00:00-05:00"),
      status: "scheduled",
    },
    {
      matchNumber: 83,
      stageSlug: "round_of_16",
      homeTeamPlaceholder: "1st Group J",
      awayTeamPlaceholder: "2nd Group I",
      venueCity: "Philadelphia",
      scheduledAt: new Date("2026-07-03T13:00:00-04:00"),
      status: "scheduled",
    },
    {
      matchNumber: 84,
      stageSlug: "round_of_16",
      homeTeamPlaceholder: "1st Group L",
      awayTeamPlaceholder: "2nd Group K",
      venueCity: "Arlington",
      scheduledAt: new Date("2026-07-03T19:00:00-05:00"),
      status: "scheduled",
    },
    {
      matchNumber: 85,
      stageSlug: "round_of_16",
      homeTeamPlaceholder: "3rd Group A/C/E/G",
      awayTeamPlaceholder: "3rd Group B/D/F/H",
      venueCity: "Seattle",
      scheduledAt: new Date("2026-06-28T12:00:00-07:00"),
      status: "scheduled",
    },
    {
      matchNumber: 86,
      stageSlug: "round_of_16",
      homeTeamPlaceholder: "3rd Group A/C/E/I",
      awayTeamPlaceholder: "3rd Group B/D/F/J",
      venueCity: "Vancouver",
      scheduledAt: new Date("2026-06-29T18:00:00-07:00"),
      status: "scheduled",
    },
    {
      matchNumber: 87,
      stageSlug: "round_of_16",
      homeTeamPlaceholder: "3rd Group A/C/G/K",
      awayTeamPlaceholder: "3rd Group B/D/H/L",
      venueCity: "Mexico City",
      scheduledAt: new Date("2026-06-30T18:00:00-05:00"),
      status: "scheduled",
    },
    {
      matchNumber: 88,
      stageSlug: "round_of_16",
      homeTeamPlaceholder: "3rd Group A/E/I/K",
      awayTeamPlaceholder: "3rd Group B/F/J/L",
      venueCity: "Monterrey",
      scheduledAt: new Date("2026-07-01T18:00:00-06:00"),
      status: "scheduled",
    },
    // Quarter-finals (Matches 89-92) - corrected to use quarter_finals stage
    {
      matchNumber: 89,
      stageSlug: "quarter_finals",
      homeTeamPlaceholder: "Winner Match 73",
      awayTeamPlaceholder: "Winner Match 75",
      venueCity: "Foxborough",
      scheduledAt: new Date("2026-07-09T15:00:00-04:00"),
      status: "scheduled",
    },
    {
      matchNumber: 90,
      stageSlug: "quarter_finals",
      homeTeamPlaceholder: "Winner Match 74",
      awayTeamPlaceholder: "Winner Match 76",
      venueCity: "Inglewood",
      scheduledAt: new Date("2026-07-09T19:00:00-07:00"),
      status: "scheduled",
    },
    {
      matchNumber: 91,
      stageSlug: "quarter_finals",
      homeTeamPlaceholder: "Winner Match 77",
      awayTeamPlaceholder: "Winner Match 79",
      venueCity: "Miami Gardens",
      scheduledAt: new Date("2026-07-10T15:00:00-04:00"),
      status: "scheduled",
    },
    {
      matchNumber: 92,
      stageSlug: "quarter_finals",
      homeTeamPlaceholder: "Winner Match 78",
      awayTeamPlaceholder: "Winner Match 80",
      venueCity: "Kansas City",
      scheduledAt: new Date("2026-07-10T19:00:00-05:00"),
      status: "scheduled",
    },
    // Semi-finals (Matches 93-94)
    {
      matchNumber: 93,
      stageSlug: "semi_finals",
      homeTeamPlaceholder: "Winner Match 89",
      awayTeamPlaceholder: "Winner Match 90",
      venueCity: "Arlington",
      scheduledAt: new Date("2026-07-14T15:00:00-05:00"),
      status: "scheduled",
    },
    {
      matchNumber: 94,
      stageSlug: "semi_finals",
      homeTeamPlaceholder: "Winner Match 91",
      awayTeamPlaceholder: "Winner Match 92",
      venueCity: "Atlanta",
      scheduledAt: new Date("2026-07-15T15:00:00-04:00"),
      status: "scheduled",
    },
    // Third Place (Match 95)
    {
      matchNumber: 95,
      stageSlug: "third_place",
      homeTeamPlaceholder: "Loser Match 93",
      awayTeamPlaceholder: "Loser Match 94",
      venueCity: "Miami Gardens",
      scheduledAt: new Date("2026-07-18T17:00:00-04:00"),
      status: "scheduled",
    },
    // Final (Match 96)
    {
      matchNumber: 96,
      stageSlug: "final",
      homeTeamPlaceholder: "Winner Match 93",
      awayTeamPlaceholder: "Winner Match 94",
      venueCity: "East Rutherford",
      scheduledAt: new Date("2026-07-19T15:00:00-04:00"),
      status: "scheduled",
    },
  ];

  // Resolve foreign keys and insert matches
  const resolvedMatches: NewMatch[] = matchesData.map((match) => ({
    matchNumber: match.matchNumber,
    stageId: stageIdBySlug.get(match.stageSlug)!,
    homeTeamId: match.homeTeamCode
      ? teamIdByCode.get(match.homeTeamCode)!
      : null,
    awayTeamId: match.awayTeamCode
      ? teamIdByCode.get(match.awayTeamCode)!
      : null,
    homeTeamPlaceholder: match.homeTeamPlaceholder || null,
    awayTeamPlaceholder: match.awayTeamPlaceholder || null,
    venueId: venueIdByCity.get(match.venueCity)!,
    scheduledAt: match.scheduledAt,
    status: match.status,
  }));

  await db.insert(matches).values(resolvedMatches);
  console.log(`✅ Inserted ${resolvedMatches.length} matches`);

  console.log("✨ Seed completed successfully!");
}

seed()
  .catch((error) => {
    console.error("❌ Seed failed:", error);
    process.exit(1);
  })
  .finally(() => {
    process.exit(0);
  });
